### ISSUE TITLE
Quickstart Guide Issue

### ISSUE THREAD

**Issue by daslicht** [compoundjs/guides#19]
Hello,

I have followed the quickstart guide:
https://github.com/compoundjs/guides/blob/master/basics/crash-course.md

But when I try to start the todo-list-app i get the following error:

```
daslicht:todo-list-app daslicht$ node server.js

/Users/daslicht/compound/todo-list-app/config/environment.js:11
        app.loadConfigs(__dirname);
            ^
TypeError: Object function app(req, res, next){ app.handle(req, res, next); } has no method 'loadConfigs'
    at Function.<anonymous> (/Users/daslicht/compound/todo-list-app/config/environment.js:11:13)
    at Function.app.configure (/Users/daslicht/compound/todo-list-app/node_modules/express/lib/application.js:392:61)
    at module.exports (/Users/daslicht/compound/todo-list-app/config/environment.js:6:9)
    at requireIfExists (/Users/daslicht/compound/todo-list-app/node_modules/compound/lib/compound.js:233:27)
    at CompoundServer.configureApp [as configure] (/Users/daslicht/compound/todo-list-app/node_modules/compound/lib/compound.js:215:5)
    at CompoundServer.initCompound (/Users/daslicht/compound/todo-list-app/node_modules/compound/lib/compound.js:111:18)
    at CompoundServer.initCompoundServer [as init] (/Users/daslicht/compound/todo-list-app/node_modules/compound/lib/server/compound.js:53:29)
    at /Users/daslicht/compound/todo-list-app/node_modules/compound/lib/compound.js:79:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:901:3
$ 

```

what am I missing ?

**Comment by anatoliychakkaev** [comment]
Just typo. Fixed and published over current version (compound@1.1.7-8).
Thanks!

**Comment by daslicht** [comment]
ok lets try it again :)

**Comment by anatoliychakkaev** [comment]
Actually it should be `compound.loadConfigs` and not `app.loadConfig`

On Wed, Jul 24, 2013 at 12:43 AM, daslicht notifications@github.com wrote:

> ok lets try it again :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/compoundjs/guides/issues/19#issuecomment-21444536
> .

## 

Thanks,
Anatoliy Chakkaev

**Comment by daslicht** [comment]
when i tried to sudo npm install compound -g i get : 

/usr/local/bin/rw -> /usr/local/lib/node_modules/compound/bin/compound.js
npm WARN unmet dependency /usr/local/lib/node_modules/mongo-express/node_modules/express/node_modules/connect/node_modules/send requires fresh@'0.1.0' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/mongo-express/node_modules/express/node_modules/connect/node_modules/fresh,
npm WARN unmet dependency which is version 0.0.1
