### ISSUE TITLE
Unexpected string

### ISSUE THREAD

**Issue by arunabhdas** [compoundjs/guides#24]
After running 
==> compound init myapp
and
==> npm install
and
==> compound generate scaffold list name
and
==> node .
I get the following error : 
express deprecated app.configure: Check app.get('env') in an if statement config/environment.js:6:9
connect deprecated methodOverride: use method-override npm module instead config/environment.js:16:25
express deprecated app.configure: Check app.get('env') in an if statement config/environments/development.js:6:9
undefined:26
List = describe 'List', ->
                ^^^^^^
SyntaxError: Unexpected string
  at Function (native)
  at loadSchema (/work-ssd/compoundjs/myapp/node_modules/jugglingdb/lib/railway.js:107:18)
  at init (/work-ssd/compoundjs/myapp/node_modules/jugglingdb/lib/railway.js:74:9)
  at initialize (/work-ssd/compoundjs/myapp/node_modules/jugglingdb/index.js:94:13)
  at Object.exports.init (/work-ssd/compoundjs/myapp/node_modules/jugglingdb/index.js:83:9)
  at /work-ssd/compoundjs/myapp/node_modules/compound/lib/server/extensions.js:27:23
  at Array.forEach (native)
  at init (/work-ssd/compoundjs/myapp/node_modules/compound/lib/server/extensions.js:25:18)
  at CompoundServer.module.exports [as extensions](/work-ssd/compoundjs/myapp/node_modules/compound/lib/server/extensions.js:18:9)
  at CompoundServer.initCompound (/work-ssd/compoundjs/myapp/node_modules/compound/lib/compound.js:127:14)
  at CompoundServer.initCompoundServer [as init](/work-ssd/compoundjs/myapp/node_modules/compound/lib/server/compound.js:54:29)
  at /work-ssd/compoundjs/myapp/node_modules/compound/lib/compound.js:84:22
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by nsallis** [comment]
I know this is late, but the problem seams to be in schema.js. The generated code:
 `List = describe 'List', ->
     property('name', String);
     set 'restPath', pathTo.lists
`

does not work. Replace it with `define ('List', function(){
        property('name', String);
        set('restPath', pathTo.lists);
    });`

like the example says. You may also have to add this line to your list.js model definition: `name: { type: String };`. I'm not sure that gets defined automatically.

**Comment by iekumdario** [comment]
I was struggling with this too. The generator is creating CoffeeScript code. Renaming the file to schema.coffee and changing the block comment to ### instead of /* */ (or deleting it) is another workaround. My guess was that to use the generator with CoffeeScript you had to use --coffee but it does so without the flag. Also the model is created with no attributes.

**Comment by yohanesgultom** [comment]
After some digging, I found out that the problem is caused by outdated `co-generators` code in npm registry. Pointing directly to the github repository in generated/scaffolded project's `package.json` & reinstalling the packages fix this issue:

```
    "devDependencies": {
       ...
        "co-generators": "git://github.com/compoundjs/generators.git"
    },
```
